version: 1.0.{build}
image: Visual Studio 2022
install:
  - ps: Invoke-WebRequest "https://dot.net/v1/dotnet-install.ps1" -OutFile "$env:TEMP\dotnet-install.ps1"
  - ps: '& "$env:TEMP\dotnet-install.ps1" -Channel 10.0 -InstallDir "C:\Program Files\dotnet"'
before_build:
- cmd: nuget restore ./source/Stateless.WorkflowEngine.sln
build:
  project: source/Stateless.WorkflowEngine.sln
  verbosity: minimal
test:
  categories:
    except:
    - RequiresRavenDb
    - RequiresMongoDb